# docker-compose.yml
version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - ENVIRONMENT=development
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=86400
    volumes:
      - .:/app
